### ISSUE TITLE
Numpy 2.0 support

### ISSUE THREAD

**Issue by nikhilpodila** [ros-perception/vision_opencv#535]
Similar to [this error](https://github.com/opencv/opencv-python/issues/943#issuecomment-2171817940) previously in opencv, I get the following error when importing `cv-bridge`:

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/ros/humble/lib/my_driver/my_driver_node", line 33, in <module>
    sys.exit(load_entry_point('my-driver==0.1.0', 'console_scripts', 'my_driver_node')())
  File "/opt/ros/humble/lib/my_driver/my_driver_node", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/ros/humble/lib/python3.10/site-packages/my_driver/my_driver_node.py", line 8, in <module>
    from cv_bridge import CvBridge
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/cv_bridge/__init__.py", line 6, in <module>
    from cv_bridge.boost.cv_bridge_boost import cvtColorForDisplay, getCvType
AttributeError: _ARRAY_API not found
```

It looks like `cv-bridge` installed via `apt` or `pip` is not yet built with numpy 2.0. Is the support for numpy 2.0 coming soon?

**Comment by 23pointsNorth** [comment]
From what I can see, the package relies on python-numpy in package.xml

Checking the version 
```
apt search python3-numpy
Sorting... Done
Full Text Search... Done
python3-numpy/jammy-updates,jammy-security,now 1:1.21.5-1ubuntu22.04.1 amd64 [installed,automatic]
  Fast array facility to the Python 3 language
```
Returns numpy at 1.21.5

So from what I can see we need to also submit a request to bump the numpy version in apt.

**Comment by ijnek** [comment]
Currently, Ubuntu Jammy and Ubuntu Noble use NumPy 1.21 and 1.26 as their default binary versions, so there hasn't been a strong push to adopt NumPy 2 yet. However, pull requests to add support are always welcome.

**Comment by dheerubhai-101** [comment]
Hi @ijnek so what do you think should be done? From what is shown, it feels like more of an Debian packages to be upgraded than ROS packages. Or should there be any changes done like https://github.com/opencv/opencv-python/issues/943 

I am assuming that the rolling version is already built on NumPy 2.0.

**Comment by traversaro** [comment]
> I am assuming that the rolling version is already built on NumPy 2.0.

Probably not? For Ubuntu, Rolling as of May 2025 targets Ubuntu 24.04 (see https://github.com/ros-infrastructure/rep/pull/421), and that platform ships NumPy 1.26, see https://repology.org/project/python:numpy/versions . I guess the first Ubuntu LTS version taht will ship with NumPy 2.* will be Ubuntu 26.04 .

**Comment by Benjamin-Tan** [comment]
Since the apt version of numpy is not version 2.0 for the near future, would it be better to package this in pip wheel instead to support numpy 2.0?

**Comment by traversaro** [comment]
> Since the apt version of numpy is not version 2.0 for the near future, would it be better to package this in pip wheel instead to support numpy 2.0?

The tricky part there is how to package the whole dependency chain of `vision_opencv` inside a PyPI package index, see https://discourse.ros.org/t/experimental-python-package-index-for-ros/10366 and https://github.com/ros2/ros2/issues/1094 . Nvidia does something in that direction by basically packaging a whole ros2 install prefix in a single wheel in https://pypi.nvidia.com/isaacsim-ros2/, but I am not sure how maintainable that approach is.

**Comment by Benjamin-Tan** [comment]
It seems that python/cv_bridge only requires opencv and numpy2, any other dependency that is required? It may be just a recompilation.

**Comment by traversaro** [comment]
> It seems that python/cv_bridge only requires opencv and numpy2, any other dependency that is required? It may be just a recompilation.

I am not sure what you are proposing, I guess `cv_bridge` also depends on boost_python, rclcpp and so on and so forth (see https://github.com/ros-perception/vision_opencv/blob/27de9ecf9862e6fba509b7e49e3c2511c7d11627/cv_bridge/src/CMakeLists.txt#L35-L49). I would you include and redistribute that as part of a PyPI package, while keeping compatibility with ROS distributions?

**Comment by Benjamin-Tan** [comment]
Not trying to support numpy 2 for the entire ROS distributions, but only for cv_bridge. I tried the following (not very neat but it seems to work):
- rosdep install the necessary dependencies in 'package.xml'
- pip install `numpy>=2.0`
- compile cv_bridge, which would generate libcv_bridge.so and boost/cv_bridge_boost.so
- 1 small fix on the python/cv_bridge/core.py and it is working good with all the test.

**Comment by traversaro** [comment]
Ok, so you are building a Python wheel using a mixture of apt and pip, with some incompatible packages (numpy 1 installed by apt, and numpy 2 installed by pip). The generated artifacts will depend on the specific OpenCV ABI (related to the Ubuntu version you are using) and the specific rclcpp ABI (related to the ROS version are you using). 

How do yo envision distributing such artifact (i.e. "to package this in pip wheel" as mentioned before)?

**Comment by Benjamin-Tan** [comment]
Yeah I agree with you. I have only tried ros humble and not the other distros. I think the pip wheel basically contains the cv_bridge/core.py, libcv_bridge.so, boost/cv_bridge_boost.so. The wheel generation could be one-off or via github actions onto pypi.

**Comment by ramzinc** [comment]
@Benjamin-Tan I am trying to do what you did though not to distribute the package but use it locally, can you share your fix for the `cv_bridge/core.py` ?

**Comment by Benjamin-Tan** [comment]
@ramzinc @ijnek @traversaro Please have a look at #556 as it may eventually help to resolve this issue of numpy 2.0 support.

**Comment by traversaro** [comment]
> [@ramzinc](https://github.com/ramzinc) [@ijnek](https://github.com/ijnek) [@traversaro](https://github.com/traversaro) Please have a look at [#556](https://github.com/ros-perception/vision_opencv/pull/556) as it may eventually help to resolve this issue of numpy 2.0 support.

`nanobind` is super cool and so the improvement may be interesting, but I am probably missing something here on how this is related to the issue here. The problem here is that apt packages of `vision_opencv` are built against numpy, at least until ROS package itself will migrate to a distro that uses numpy 2.0 (Ubuntu 26.04?). If I am not wrong, the problem lies in linking numpy 1.*, it does not depend on the specific technology (nanobind, pybind11, boost-python, swig) used to actually generate the bindings.

**Comment by traversaro** [comment]
Ah, I see, you moved the conversion part to not use numpy ABI at all, interesting.
